//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 BottleCap.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDD_BottleCap_FORM              101
#define IDR_MAINFRAME                   128
#define IDR_MPCHECTYPE                  129
#define IDB_COMPANY                     132
#define IDD_DLG_TESTCIPHER              133
#define IDD_DLG_SELECT_PRODUCT          134
#define IDD_DLG_STATISTIC               135
#define IDI_ICON_MP                     136
#define IDI_ICON_MP1                    137
#define IDI_ICON_STOP                   138
#define IDI_ICON_QUIT                   140
#define IDI_ICON_START                  143
#define IDI_ICON_STATICTIC              144
#define IDI_ICON_PARAM                  145
#define IDI_ICON_RECORD                 146
#define IDI_ICON_MODEL                  147
#define IDD_DLG_SAVE_IMAGE              148
#define IDD_DLG_SYSTEM_CONFIG           149
#define IDD_DLG_SHOW_IMAGE              150
#define IDD_DLG_NEW_MODEL               151
#define IDD_DLG_PAGE1                   152
#define IDD_DLG_PAGE2                   153
#define IDI_ICON_BOTTLE                 153
#define IDD_DLG_ALRAM                   154
#define IDI_ICON_ALARM                  157
#define IDI_ICON_ZERO                   158
#define IDI_ICON_DEFECT_STATISTIC       159
#define IDD_DLG_DEFECT_PAGE_1           160
#define IDD_DLG_DEFECT                  161
#define IDD_DLG_DEFECT_PAGE_2           162
#define IDD_DLG_ALRAM_POS               163
#define IDD_DLG_ALRAM_STOP_COUNT        164
#define IDD_DLG_CAM_TEST                165
#define IDD_DLG_SETCIPHER               166
#define IDD_DLG_LOGIN                   167
#define IDD_DLG_USER_ADM                168
#define IDD_DLG_ADD_USER                169
#define IDD_DLG_MODIFY_CIPHER           170
#define IDC_PIC1                        1000
#define IDC_ALG1                        1001
#define IDC_BTN_QUIT                    1002
#define IDC_BTN_START                   1003
#define IDC_BTN_PARAM                   1004
#define IDC_BTN_MOULD_ADM               1005
#define IDC_BTN_STATISTIC               1006
#define IDC_STATIC_PIC                  1007
#define IDC_TOTAL_LABEL                 1008
#define IDC_TOTAL_GOOD_LABEL            1009
#define IDC_TOTAL_GOOD_RATIO_LABEL      1010
#define IDC_MODEL_NAME_LABEL            1011
#define IDC_TOTAL_DATA                  1012
#define IDC_TOTAL_GOOD_DATA             1013
#define IDC_TOTAL_GOOD_RATIO_DATA       1014
#define IDC_MODEL_NAME_DATA             1015
#define IDC_STATIC_INFO                 1016
#define IDC_STATIC_ACT                  1017
#define IDC_BTN_RECORD                  1018
#define IDC_LIST1                       1019
#define IDC_GOOD_LABEL_1                1019
#define IDC_GOOD_LABEL1                 1019
#define IDC_LOGO                        1020
#define IDC_LIST2                       1020
#define IDC_LIST_DEBUG                  1020
#define IDC_STATIC_YEAR                 1021
#define IDC_LIST_USER                   1021
#define IDC_STATIC_HOUR                 1022
#define IDC_CIPHER_TEXT                 1022
#define IDC_EDIT_NEW_MODEL_NAME         1023
#define IDC_PIC2                        1023
#define IDC_BUTTON_NEW                  1024
#define IDC_ALG2                        1024
#define IDC_GOODRATIO_LABEL1            1025
#define IDC_PIC3                        1025
#define IDC_BUTTON_DELETE               1026
#define IDC_GOOD_LABEL2                 1026
#define IDC_ALG3                        1026
#define IDC_GOODRATIO_LABEL2            1027
#define IDC_GOOD_DATA1                  1028
#define IDC_LIST_MODEL                  1029
#define IDC_GOODRATIO_DATA1             1029
#define IDC_CHECK_DATE                  1030
#define IDC_GOOD_DATA2                  1030
#define IDC_START_TIME                  1031
#define IDC_GOODRATIO_DATA2             1031
#define IDC_STOP_TIME                   1032
#define IDC_BTN_DEFECT_STATISTICS       1032
#define IDC_BTN_ZERO                    1033
#define IDC_SPEED_LABEL                 1034
#define IDC_SPEED_DATA                  1035
#define IDC_BTN_QUERY                   1036
#define IDC_USER_LABEL                  1036
#define IDC_BTN_EXCEL                   1037
#define IDC_WINDOW_TITLE                1038
#define IDC_SAVE_IMAGE                  1039
#define IDC_SYSTEM_CONFIG               1040
#define IDC_IOCARD                      1041
#define IDC_ADV_MODE                    1042
#define IDC_CIRCLE                      1043
#define IDC_STOP_SAVE_IMAGE             1043
#define IDC_NO_CIRCLE                   1044
#define IDC_USER_ADM                    1044
#define IDC_USER_DATA                   1045
#define IDC_RADIO_ERROR                 1046
#define IDC_EDIT_GRAB                   1047
#define IDC_EDIT_ERROR                  1048
#define IDC_EDIT_SHOW_TIME              1048
#define IDC_RADIO_NONE                  1050
#define IDC_RADIO_ALL                   1051
#define IDC_RADIO_GRAB                  1052
#define IDC_EDIT_SAVE_IMAGE_COUNT       1052
#define IDC_RADIO_GOOD                  1053
#define IDC_EDIT_CHECK_TIME1            1053
#define IDC_RADIO_BAD                   1054
#define IDC_CHECK_BAYER                 1054
#define IDC_RADIO_NoBottle              1055
#define IDC_EDIT_RED                    1055
#define IDC_EDIT_GREEN                  1056
#define IDC_BTN_IMAGE                   1056
#define IDC_EDIT_BLUE                   1057
#define IDC_CHECK_KICK1                 1058
#define IDC_RADIO_BODY_SHAPE_1          1059
#define IDC_CHECK_KICK2                 1059
#define IDC_RADIO_BODY_SHAPE_2          1060
#define IDC_TAB1                        1060
#define IDC_CHECK_BAYER2                1060
#define IDC_RADIO_HEAD_SHAPE_1          1061
#define IDC_EDIT_RED2                   1061
#define IDC_PIC_ALARM                   1061
#define IDC_RADIO_HEAD_SHAPE_2          1062
#define IDC_EDIT_GREEN2                 1062
#define IDC_ALARM_INFO                  1062
#define IDC_EDIT_BLUE2                  1063
#define IDC_COMBO_NAME                  1063
#define IDC_EDIT_CHECK_TIME2            1064
#define IDC_COMBO_SPEC                  1064
#define IDC_CHECK_KICK3                 1064
#define IDC_EDIT_PE_GAP                 1065
#define IDC_COMBO_PERCENT               1065
#define IDC_EDIT_LABEL_ERROR_COUNT      1065
#define IDC_EDIT_LABEL_ERROR_COUNT12    1065
#define IDC_EDIT_LABEL_ERROR_COUNT2     1065
#define IDC_CHECK_BAYER3                1065
#define IDC_EDIT_LABEL_ERROR_COUNT1     1066
#define IDC_EDIT_RED3                   1067
#define IDC_EDIT_GREEN3                 1068
#define IDC_EDIT_BLUE3                  1069
#define IDC_WS_1                        1072
#define IDC_WS_2                        1073
#define IDC_STATIC_INQUIRY              1074
#define IDC_START_DATE                  1076
#define IDC_STOP_DATE                   1077
#define IDC_STATIC_START                1078
#define IDC_STATIC_STOP                 1079
#define IDC_CHECK_MODEL_NAME            1080
#define IDC_COMBO_MODEL_NAME            1081
#define IDC_BTN_INQUIRY                 1082
#define IDC_RADIO_IN_HIGH               1083
#define IDC_RADIO_IN_LOW                1084
#define IDC_EDIT_KICK_OFFSET            1085
#define IDC_EDIT_SINGLE_NUM             1086
#define IDC_EDIT_TWO_NUM                1087
#define IDC_CHECK1                      1087
#define IDC_CHECK2                      1088
#define IDC_RADIO_KICK_ALL              1088
#define IDC_RADIO_KICK_NO               1089
#define IDC_RADIO_CAM1                  1089
#define IDC_CHECK3                      1089
#define IDC_RADIO_KICK_DIFF             1090
#define IDC_RADIO_CAM2                  1090
#define IDC_RADIO_KICK_NORMAL           1091
#define IDC_RADIO_CAM3                  1091
#define IDC_BTN_STOP                    1092
#define IDC_EDIT_WIDTH                  1093
#define IDC_EDIT_HEIGHT                 1094
#define IDC_EDIT_OFFSETX                1095
#define IDC_EDIT_OFFSETY                1096
#define IDC_EDIT_EXPOSURE_TIME          1097
#define IDC_COMBO_MODELNAME             1098
#define IDC_BTN_SAVE                    1100
#define IDC_CIPHER_OLD                  1101
#define IDC_CIPHER_NEW1                 1102
#define IDC_CIPHER_NEW2                 1103
#define IDC_BTNSETCIPHER                1104
#define IDC_EDIT_USER                   1105
#define IDC_EDIT_PASSWORD               1106
#define IDC_BTN_ADM_ADD                 1106
#define IDC_BTN_ADM_DELETE              1107
#define IDC_EDIT_NEW_PASSWORD           1107
#define IDC_BTN_ADM_MODIFY              1108
#define IDC_BTN_DEBUG_ADD               1109
#define IDC_BTN_DEBUG_DELETE            1110
#define IDC_BTN_DEBUG_MODIFY            1111
#define IDC_BTN_USER_ADD                1112
#define IDC_BTN_USER_DELETE             1113
#define IDC_BTN_USER_MODIFY             1114
#define IDC_LIST_ADM                    1115
#define IDC_EDIT_OLD_PASSWORD           1116
#define IDC_RADIO_SaveImgObj_Alg        1119
#define IDC_RADIO_SaveImgObj_MObj       1120
#define IDC_RADIO_SaveImgObj_Obj        1120
#define IDC_RADIO_GRAB2                 1121
#define IDC_RADIO1                      1121
#define IDC_RADIO2                      1122
#define IDC_RADIO3                      1123
#define IDC_RADIO4                      1124
#define IDC_RADIO5                      1125
#define IDC_RADIO6                      1126

#define IDC_MP                          1037
#define ID_INDICATOR_GRAB               61446
#define ID_INDICATOR_CHECK              61447
#define ID_INDICATOR_ERROR              61448
#define ID_INDICATOR_OPERATION          61449

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1122
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
