// CHINESE.h: interface for the English Language Pack.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_CHINESE_LP_H__5F4AEA7E_E637_4595_8F13_D6EE727C71D4__INCLUDED_)
#define AFX_CHINESE_LP_H__5F4AEA7E_E637_4595_8F13_D6EE727C71D4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

extern "C" __declspec(dllexport) void GetText(char* chText, int nDoWhat, ...);

#endif // !defined(AFX_CHINESE_LP_H__5F4AEA7E_E637_4595_8F13_D6EE727C71D4__INCLUDED_)