//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DemoProject.rc
//
#define IDC_BTN_EXIT2                   3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DEMOPROJECT_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_DLG_MDLOP                   130
#define IDD_DLG_PROCESS_TEST            131
#define IDI_ICON1                       137
#define IDI_ICON_MODEL                  138
#define IDD_DLG_EXIT                    143
#define IDD_DLG_FILELIST                144
#define IDD_DLG_MODEL                   145
#define IDI_ICON_FLY1                   146
#define IDI_ICON_FLY2                   148
#define IDI_ICON_FLY3                   149
#define IDI_ICON_FLY4                   150
#define IDI_ICON_FLY5                   151
#define IDI_ICON_FLY6                   152
#define IDI_ICON_FLY7                   153
#define IDI_ICON_FLY8                   155
#define IDD_DIALOG_START                156
#define IDR_ABOUT_CAPSULE               156
#define IDD_DLG_START                   156
#define IDR_ABOUT_STOPPER               157
#define IDB_BITMAP_LOGO                 158
#define IDD_DLG_NEWMODEL                163
#define IDD_DLG_LANGUAGE                167
#define IDD_DLG_INSPSEL                 168
#define IDD_DLG_INSP                    168
#define IDD_DLG_NUMWS                   172
#define IDD_DLG_PARKOUR                 173
#define IDI_ICON_DH                     178
#define IDB_BITMAP_DH                   183
#define IDB_BITMAP_CAMERA               189
#define IDD_ModelLog                    198
#define IDI_ICON2                       201
#define IDC_NEWMODEL                    1001
#define IDC_TAB1                        1005
#define IDC_STATIC_1                    1006
#define IDC_STATIC_2                    1007
#define IDC_STATIC_3                    1008
#define IDC_STATIC_4                    1009
#define IDC_STATIC_5                    1010
#define IDC_MODELLIST                   1012
#define IDC_BTN_SAVEMODEL               1013
#define IDC_EDIT1                       1014
#define IDC_BTNREADMODEL                1015
#define IDC_BTN_DELETE                  1016
#define IDC_BTN_SETD                    1017
#define IDC_BTN_UPDMDL                  1018
#define IDC_BTN_SAVESINGLEMODEL         1019
#define IDC_BUTTON_MDL                  1022
#define IDC_STATIC_MDAREA               1023
#define IDC_STATIC_IMG                  1024
#define IDC_STATIC_BCK                  1025
#define IDC_STATIC_MLIST                1026
#define IDC_STATIC_NEWNAME              1027
#define IDC_STATIC_KJ                   1030
#define IDC_BTN_MLIST                   1032
#define IDC_LIST_PROCESS                1033
#define IDC_STATIC_CMODEL               1034
#define IDC_STATIC_FILEBACK             1039
#define IDC_BTN_ERRIMG                  1040
#define IDC_BTN_GRABIMG                 1041
#define IDC_LIST_DISK                   1043
#define IDC_BTN_CAPIMG                  1044
#define IDC_BTN_CLRST                   1045
#define IDC_LIST_DISK2                  1046
#define IDC_LIST_RESULT                 1047
#define IDC_BTN_CAMIMGTEST              1048
#define IDC_BTN_CTEST                   1048
#define IDC_BTN_MDLIMGTEST              1049
#define IDC_LIST_DISK3                  1049
#define IDC_BTN_LISTIMGTEST             1050
#define IDC_LIST_DISK4                  1050
#define IDC_LIST_BROWSER                1051
#define IDC_LIST_DISK5                  1051
#define IDC_LIST2                       1052
#define IDC_LIST_BROWSER2               1052
#define IDC_BTN_LANDE                   1053
#define IDC_STATIC_VERSION              1054
#define IDC_BTN_EXIT                    1055
#define IDC_STATIC_CURPATH              1055
#define IDC_BTN_CANCEL                  1056
#define IDC_LIST_BROWSER3               1056
#define IDC_STATIC_FLY1                 1057
#define IDC_LIST_BROWSER4               1057
#define IDC_LIST_BROWSER5               1058
#define IDC_STATIC_BACK                 1060
#define IDC_PROG_LOADING                1061
#define IDC_STATIC_LOADING              1062
#define IDC_STATIC_LOGO                 1063
#define IDC_STATIC_PROG                 1067
#define IDC_LIST_BROWSER1               1068
#define IDC_LIST_DISK1                  1069
#define IDC_STATIC_LL                   1070
#define IDC_BTN_PARKOUR                 1071
#define IDC_STATIC_INFO                 1072
#define IDC_STATIC_FILE                 1073
#define IDC_STATIC_DISK                 1074
#define IDC_BTN_CONFIRM                 1075
#define IDC_EDIT_NAME                   1076
#define IDC_STATIC_DEMOV                1077
#define IDC_EDIT_CURPATH                1078
#define IDC_STATIC_COMP                 1079
#define IDC_STATIC_N                    1080
#define IDC_BTN_LANGUAGE                1082
#define IDC_BTN_INSP                    1083
#define IDC_EDIT_NUMWS                  1084
#define IDC_CHECK_FROMSEL               1085
#define IDC_CHECK_LOOP                  1086
#define IDC_CHECK_STOPBAD               1087
#define IDC_CHECK_STOPGOOD              1088
#define IDC_CHECK_STOPEXP               1089
#define IDC_CHECK_STOPEMP               1090
#define IDC_STATIC_FLY2                 1091
#define IDC_EDIT_INTERVAL               1091
#define IDOK_ABOUT                      1092
#define IDC_COMBO_STOPPERTYPE           1094
#define IDC_STATIC_SPLIT                1095
#define IDC_EDIT_ModelLog               1097
#define IDC_CHECK_ShowModelLog          1098
#define IDC_LIST1                       1099
#define IDC_LIST_ModelLog               1099
#define IDC_BUTTON_FoldPage             1100
#define IDC_STATIC_CMODU                1101
#define IDS_STRING_INFO                 5000
#define IDS_STRING_TITLE                5001
#define IDS_STRING_FONT                 5002
#define IDS_STRING_MDLLIST              5003
#define IDS_STRING_FILEBACK             5004
#define IDS_STRING_GRABIMG              5005
#define IDS_STRING_ERRIMG               5006
#define IDS_STRING_CAPIMG               5007
#define IDS_STRING_CLEAR                5008
#define IDS_STRING_NEWMDL1              5009
#define IDS_STRING_NEWMDL2              5010
#define IDS_STRING_DELETE               5011
#define IDS_STRING_SETD                 5012
#define IDS_STRING_SINGLESAVE           5013
#define IDS_STRING_SAVE                 5014
#define IDS_STRING_EXIT                 5015
#define IDS_STRING_LOAD                 5016
#define IDS_STRING_CREATE               5017
#define IDS_STRING_FILE                 5018
#define IDS_STRING_ABOUT                5019
#define IDS_STRING_ENDDRAW              5020
#define IDS_STRING_LOADING              5021
#define IDS_STRING_DONELOAD             5022
#define IDS_STRING_SAVEWAIT             5023
#define IDS_STRING_SAVEDONE             5024
#define IDS_STRING_SAVESUCC             5025
#define IDS_STRING_SAVEFAIL             5026
#define IDS_STRING_LOADSUC              5027
#define IDS_STRING_LOADSUC1             5028
#define IDS_STRING_LOADFAIL             5029
#define IDS_STRING_INPUTNEWNAME         5030
#define IDS_STRING_MDLNAMELONG          5031
#define IDS_STRING_MDLEXIST             5032
#define IDS_STRING_CRTSUC               5033
#define IDS_STRING_CRTFAIL              5034
#define IDS_STRING_COPYFAIL             5035
#define IDS_STRING_UNSETDLL             5036
#define IDS_STRING_UNSETOBJNUM          5037
#define IDS_STRING_UNSETOBJNUM2         5038
#define IDS_STRING_OBJNUML10            5039
#define IDS_STRING_CRTOBJFAIL           5040
#define IDS_STRING_LOADFUNCFAIL         5041
#define IDS_STRING_EXIT_LANDE1          5042
#define IDS_STRING_EXIT_LANDE2          5043
#define IDS_STRING_EXIT_EXIT            5044
#define IDS_STRING_EXIT_CANCEL          5045
#define IDS_STRING_NM                   5046
#define IDS_STRING_CANTSYS              5047
#define IDS_STRING_CANTUSE              5048
#define IDS_STRING_CANTFINDMDL          5049
#define IDS_STRING_SUCDEL               5050
#define IDS_STRING_LANGUAGE             5051
#define IDS_STRING_LANGSEL              5052
#define IDS_STRING_UNSETTED             5053
#define IDS_STRING_CONFIRM              5054
#define IDS_STRING_INPUTNUMWS           5055
#define IDS_STRIN_SETINSPOBJ            5056
#define IDS_STRING_PARKOUR              5057
#define IDS_STRING_INTERVAL             5058
#define IDS_STRING_FROMSEL              5059
#define IDS_STRING_ENDLESSRUN           5060
#define IDS_STRING_BADSTOP              5061
#define IDS_STRING_GOODSTOP             5062
#define IDS_STRING_EXPSTOP              5063
#define IDS_STRING_EMPSTOP              5064
#define IDS_STRING_START                5065
#define IDS_STRING_STOP                 5066
#define IDS_STRING_INITIALIZE           5067
#define IDS_STRING_STOPPERTYPECHANGE    5068
#define IDS_STRING_STOPPERTYPE          5069
#define IDS_STRING_5070                 5070
#define IDS_STRING_5071                 5071
#define IDS_STRING_APPNAME              5072

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
